name: Publish .NET SDK

on:
  workflow_dispatch:

jobs:
  publish-dotnet:
    runs-on: windows-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: sdk-dotnet
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore
      - name: Pack
        run: dotnet pack --configuration Release --no-restore --output ./output
      - name: Setup NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          nuget-version: latest
      - name: Publish
        run: dotnet nuget push output\*.nupkg -s https://api.nuget.org/v3/index.json
